module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx,css}", "./public/index.html"],
  darkMode: "class", // or 'media' or 'class'
  important: true,
  theme: {
    colors: {
      white: "#FFFFFF",
    },
    extend: {
      colors: {
        "white-2": "#FFFFFF1F",
        transparent: "transparent",
        "athens-gray": "#F3F5F8",
        "daisy-bush": "#4E2C90",
        "white-lilac": "#E9E9F8",
        "pickled-bluewood": "#383A65",
        "regent-gray": "#8892a5",
        iron: "#e0e0e3",
        "vista-blue": "#83D49D",
        punch: "#D95128",
        coral: "#FF7850",
        "yellow-orange": "#FFBA38",
        keppel: "#42A9A8",
        silver: "#C4C4C4",
        mischka: "#DADAE0",
        derby: "#FFECDC",
        "coconut-cream": "#EAF8DE",
        solitude: "#EAF6FF",
        cinnabar: "#ED3833",
        "half-colonial-White": "#FDF1D7",
        sauvignon: "#FFF7F5",
        "dark-gray": "#E8EBF0",
        "royal-blue": "#3D89E4",
        apple: "#5FBA46",
        "tree-poppy": "#F6941D",
        frozen: "#2CC4F3",
        "aqua-squeeze": "#E6F4F4",
        "catskill-white": "#E8ECF5",
        "san-marino": "#4266A9",
        "butterfly-bush": "#674F98",
        whisper: "#EFEDF5",
        monza: "#D90429",
        "west-side": "#FF8B1F",
        flamingo: "#EE4E23",
        transparent: "transparent",
        "blue-text": "#4e2c90",
        "grey-text": "#e0e0e3",
        white: "#FFFFFF",
        "modal-bg": "#000000B3",
        "gradient-1": "#8472AC",
        "gradient-2": "#6783BA",
        "dash-purple-light": "#FFF4FF",
        "dash-purple-dark": "#CC89CA",
        "dash-peach-light": "#FFF3ED",
        "dash-peach-dark": "#FFA376",
        "dash-blue-light": "#F0F8FF",
        "dash-blue-dark": "#47C0FF",
        "dash-orange-light": "#FFF7E3",
        "dash-orange-dark": "#FEB000",
        "dash-green-light": "#ECFAF3",
        "dash-green-dark": "#35C580",
        gray: "#808080",
        "success-text": "#62b1b0",
      },
      fontFamily: {
        poppins: "Poppins, sans-serif",
      },
      fontSize: {
        h4: "1.8125rem",
        h3: "1.3125rem",
        h2: "0.9375rem",
        h1: "0.8125rem",
        sub0: "0.75rem",
        sub1: "0.6875rem",
        sub2: "0.625rem",
      },
      boxShadow: {
        body: "0px 3px 6px #0000001A",
        footer: "0px -3px 10px #00000008",
        cards: "0px 4px 14px #00000019",
      },
      zIndex: {
        500: "500",
      },
    },
  },
  variants: {
    extend: {
      maxHeight: ["focus"],
    },
  },
  plugins: [],
};
